spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:member
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

redis:
  host: localhost
  port: 6379

secret-key: "7K2d64Co7ZSE66Gc7KCd7Yq466Gc7Lus7Iuc7YGs66a/7YKk"
expiration-hours: 24 # 24시간
refresh-expiration-hours: 24000 # 1000일
issuer: "member-api"